name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./server/config.ini:/config.ini:ro
    networks: [testing_net]
  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - NOMBRE=Juan1
      - APELLIDO=Perez1
      - DOCUMENTO=10007358
      - NACIMIENTO=1990-01-01
      - NUMERO=7177
    volumes:
      - ./client/config.yaml:/config.yaml:ro
      - ./data:/data:ro
    networks: [testing_net]
    depends_on: [server]
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
